09:46:35 AM: DEBUG: [logger_base.py: 14 Mensaje a nivel debug]
09:46:35 AM: INFO: [logger_base.py: 15 Mensaje a nivel info]
09:46:35 AM: WARNING: [logger_base.py: 16 Mensaje a nivel warning]
09:46:35 AM: ERROR: [logger_base.py: 17 Mensaje a nivel error]
09:46:35 AM: CRITICAL: [logger_base.py: 18 Mensaje a nivel critico]
10:03:49 AM: DEBUG: [persona.py: 49 
            Id: 1, Nombre: juan,
            apellido: Perez, email: jperez@gmail.com
         ]
10:06:07 AM: DEBUG: [persona.py: 49 
            Id: 1, Nombre: juan,
            apellido: Perez, email: jperez@gmail.com
         ]
10:08:42 AM: DEBUG: [persona.py: 49 
            Id: 1, Nombre: juan,
            apellido: Perez, email: jperez@gmail.com
         ]
10:08:42 AM: DEBUG: [persona.py: 52 
            Id: None, Nombre: juan,
            apellido: Perez, email: jperez@gmail.com
         ]
10:08:42 AM: DEBUG: [persona.py: 55 
            Id: None, Nombre: juan,
            apellido: Perez, email: jperez@gmail.com
         ]
10:09:30 AM: DEBUG: [persona.py: 55 
            Id: 1, Nombre: None,
            apellido: None, email: None
         ]
10:30:55 AM: DEBUG: [conexion.py: 22 Ocurrio una excepcion invalid dsn: invalid connection option "passwd"
]
10:55:16 AM: DEBUG: [conexion.py: 22 Ocurrio una excepcion invalid dsn: invalid connection option "passwd"
]
01:14:35 PM: INFO: [menu_app_usuario.py: 20 Salimos de la aplicación]
10:11:58 AM: DEBUG: [logger_base.py: 14 Mensaje a nivel debug]
10:11:58 AM: INFO: [logger_base.py: 15 Mensaje a nivel info]
10:11:58 AM: WARNING: [logger_base.py: 16 Mensaje a nivel warning]
10:11:58 AM: ERROR: [logger_base.py: 17 Mensaje a nivel error]
10:11:58 AM: CRITICAL: [logger_base.py: 18 Mensaje a nivel critico]
